-- Database script to initialise woorinaru schema
-- CREATE DATABASE IF NOT EXISTS `woorinaru`;
-- USE `woorinaru`;

SET SQL_MODE='ALLOW_INVALID_DATES';

CREATE TABLE `RESOURCE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATEDATETIME` timestamp NULL DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `UPDATEDATETIME` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `TERM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATEDATETIME` timestamp NULL DEFAULT NULL,
  `ENDDATE` date DEFAULT NULL,
  `STARTDATE` date DEFAULT NULL,
  `TERM` int(11) DEFAULT NULL,
  `UPDATEDATETIME` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `USER` (
  `USER_TYPE` varchar(1) NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATEDATETIME` timestamp NULL DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `NATIONALITY` varchar(255) DEFAULT NULL,
  `SIGNUPDATETIME` timestamp NULL DEFAULT NULL,
  `UPDATEDATETIME` timestamp NULL DEFAULT NULL,
  `GUEST` bit(1) DEFAULT NULL,
  `STAFF_ROLE` varchar(255) DEFAULT NULL,
  `TEAM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `EVENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `CREATEDATETIME` timestamp NULL DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ENDDATETIME` timestamp NULL DEFAULT NULL,
  `STARTDATETIME` timestamp NULL DEFAULT NULL,
  `UPDATEDATETIME` timestamp NULL DEFAULT NULL,
  `TERM_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKqhh1u2u8wce25e9yvq5gjw7fe` (`TERM_ID`),
  CONSTRAINT `FKqhh1u2u8wce25e9yvq5gjw7fe` FOREIGN KEY (`TERM_ID`) REFERENCES `TERM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `EVENT_STUDENT_RESERVATION` (
  `EVENT_ID` int(11) NOT NULL,
  `STUDENT_ID` int(11) NOT NULL,
  KEY `FK9mh8g5eoyopj5hbwrkm80u477` (`STUDENT_ID`),
  KEY `FK8rwuedaoweete0td6o28m72l0` (`EVENT_ID`),
  CONSTRAINT `FK8rwuedaoweete0td6o28m72l0` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`ID`),
  CONSTRAINT `FK9mh8g5eoyopj5hbwrkm80u477` FOREIGN KEY (`STUDENT_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `TERM_STAFF` (
  `TERM_ID` int(11) NOT NULL,
  `STAFF_ID` int(11) NOT NULL,
  KEY `FK6ap3vqqfb67orrp592usa9ygu` (`STAFF_ID`),
  KEY `FKroednwk4vrx1tubyc97o15xr` (`TERM_ID`),
  CONSTRAINT `FK6ap3vqqfb67orrp592usa9ygu` FOREIGN KEY (`STAFF_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `FKroednwk4vrx1tubyc97o15xr` FOREIGN KEY (`TERM_ID`) REFERENCES `TERM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `USER_RESOURCE` (
  `USER_ID` int(11) NOT NULL,
  `RESOURCE_ID` int(11) NOT NULL,
  KEY `FKox6smrrqooes7r3ng6knmcb1g` (`RESOURCE_ID`),
  KEY `FK850i75a8h45sf3f6odw9kotbh` (`USER_ID`),
  CONSTRAINT `FK850i75a8h45sf3f6odw9kotbh` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `FKox6smrrqooes7r3ng6knmcb1g` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RESOURCE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `WOORICLASS` (
  `CLASS_TYPE` varchar(1) NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATEDATETIME` timestamp NULL DEFAULT NULL,
  `UPDATEDATETIME` timestamp NULL DEFAULT NULL,
  `EVENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKhd60k5qebtjiiw0ydsaaayp58` (`EVENT_ID`),
  CONSTRAINT `FKhd60k5qebtjiiw0ydsaaayp58` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `WOORICLASS_RESOURCE` (
  `WOORICLASS_ID` int(11) NOT NULL,
  `RESOURCE_ID` int(11) NOT NULL,
  UNIQUE KEY `UK_arxkwmk2dfgyc3t9h8ix9fbxo` (`RESOURCE_ID`),
  KEY `FKfp6uwm6rldrrxabd26kmylhry` (`WOORICLASS_ID`),
  CONSTRAINT `FK84eyn41yggfdavpdye2i1uch3` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RESOURCE` (`ID`),
  CONSTRAINT `FKfp6uwm6rldrrxabd26kmylhry` FOREIGN KEY (`WOORICLASS_ID`) REFERENCES `WOORICLASS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `WOORICLASS_STAFF` (
  `WOORICLASS_ID` int(11) NOT NULL,
  `STAFF_ID` int(11) NOT NULL,
  KEY `FKi9c4r6jdnmavnqyunjkk63nrg` (`STAFF_ID`),
  KEY `FKgm578x1d2v7uy4as99txuyvkf` (`WOORICLASS_ID`),
  CONSTRAINT `FKgm578x1d2v7uy4as99txuyvkf` FOREIGN KEY (`WOORICLASS_ID`) REFERENCES `WOORICLASS` (`ID`),
  CONSTRAINT `FKi9c4r6jdnmavnqyunjkk63nrg` FOREIGN KEY (`STAFF_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `WOORICLASS_STUDENT` (
  `WOORICLASS_ID` int(11) NOT NULL,
  `STUDENT_ID` int(11) NOT NULL,
  KEY `FKbaq53mx2ecn8t2904as1s5qnp` (`STUDENT_ID`),
  KEY `FK116i79kimuw628gep4p2ljcwt` (`WOORICLASS_ID`),
  CONSTRAINT `FK116i79kimuw628gep4p2ljcwt` FOREIGN KEY (`WOORICLASS_ID`) REFERENCES `WOORICLASS` (`ID`),
  CONSTRAINT `FKbaq53mx2ecn8t2904as1s5qnp` FOREIGN KEY (`STUDENT_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci